palette = "alucard"

[aws]
style = "bold orange"

[character]
error_symbol = "[λ](bold red)"
success_symbol = "[λ](bold green)"

[cmd_duration]
style = "bold yellow"

[directory]
style = "bold green"

[git_branch]
style = "bold pink"

[git_status]
style = "bold red"

[hostname]
style = "bold purple"

[username]
format = "[$user]($style) on "
style_user = "bold cyan"

# Define Dracula PRO Alucard color palette (light theme)
[palettes.alucard]
background = "#F5F5F5"
current_line = "#CFCFDE"
foreground = "#1F1F1F"
comment = "#635D97"
cyan = "#047FB4"
green = "#198D0C"
orange = "#A34D14"
pink = "#BF185A"
purple = "#7862D0"
red = "#D74C3D"
yellow = "#9E841A"
